all:
	@echo Compiling...
	@gcc laboratory_1.c -o laboratory_1.out
	@echo Compile has ended successfuly!

run:
	@echo Start program...
	@echo --------------------------
	@./laboratory_1.out
	@echo --------------------------
	@echo Program has ended successfuly!

