all:
	@echo Compiling...
	@gcc laboratory_2.c -o laboratory_2.out
	@echo Compile has ended successfuly!

run:
	@echo Start program...
	@echo --------------------------
	@./laboratory_2.out
	@echo --------------------------
	@echo Program has ended successfuly!

